image: node:16-bullseye

stages:
  - publish

release-publish:
  stage: publish
  only:
    - release
  except:
    - tags
  script:
    - mv $NPMRC_FILE ~/.npmrc
    - npm publish

dev-publish:
  stage: publish
  only:
    - dev
  except:
    - tags
  script:
    - mv $NPMRC_FILE ~/.npmrc
    - cp package-dev.json package.json
    - npm publish