image: node:16-bullseye

stages:
  - publish

release-publish:
  stage: publish
  only:
    - release
  except:
    - tags
  script:
    - mv $NPMRC_FILE ~/.npmrc
    - npm version $(curl https://registry.npmjs.org/@xxnetwork%2fxxdk-npm | jq -r .'["dist-tags"]["latest"]' | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)
    - npm publish

dev-publish:
  stage: publish
  only:
    - dev
  except:
    - tags
  script:
    - mv $NPMRC_FILE ~/.npmrc
    - cp package-dev.json package.json
    - npm version $(curl https://registry.npmjs.org/@xxnetwork%2fxxdk-npm-dev | jq -r .'["dist-tags"]["latest"]' | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)
    - npm publish